pool:
  name: Hosted Windows 2019 with VS2019

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - /*

steps:
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: BuildOutput
