pool:
  name: Hosted Windows 2019 with VS2019

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - /*

steps:
  - task: CopyFiles@2
    inputs:
      sourceFolder: "$(Build.SourcesDirectory)"
      contents: "
      **\ProviderModule**
      **requirements.txt
      **web.config
      "
      targetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: BuildOutput
